DROP TABLE IF EXISTS notes;

CREATE TABLE notes(
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  modified TIMESTAMP DEFAULT now() NOT NULL,
  folderId TEXT REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL
);